controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

index:
  path: /hello/{name}
  controller: 'App\Controller\DefaultController::index'
